# Change these first
owner: apm87 # Your GitHub organization or username, where this repository lives
repo: Nube # The name of this repositoryy

sites:
  - name: RepejuADM
    url: https://repeju.citasturnos.com/REPEJU/login.aspx
  - name: RepejuWEB
    url: https://repeju.citasturnos.com/REPEJUWeb/welcome 
  - name: DraPaulaSolanoADM
    url: https://drapaulasolano.citasturnos.com/DraPaulaSolano/login.aspx   
  - name: DraPaulaSolanoWEB
    url: https://drapaulasolano.citasturnos.com/DraPaulaSolanoWeb/welcome 
  - name: AmcaADMM
    url: https://amca.citasturnos.com/Amca/login.aspx   
  - name: AmcaWEB
    url: https://amca.citasturnos.com/AmcaWeb/welcome 
  - name: CombexADM
    url: https://combex-im.citasturnos.com/CitasCombex-Im/login.aspx
  - name: CombexWEB
    url: https://combex-im.citasturnos.com/CitasWebCOMBEX-IM/welcome
  - name: OrbisADM
    url: https://orbis.citasturnos.com/Orbis/login.aspx
  - name: OrbisWEB
    url: https://orbis.citasturnos.com/OrbisWeb/welcome
  - name: UniversalADM
    url: https://universal.citasturnos.com/Universal/login.aspx
  - name: UniversalWEB
    url: https://universal.citasturnos.com/Universalweb
  - name: CEPMADM
    url: https://CEPM.citasturnos.com/CEPM/login.aspx
  - name: CEPMWEB
    url: https://CEPM.citasturnos.com/CEPMWeb/welcome
  - name: AcertivaCPADM
    url: https://asertivacp.citasturnos.com/AsertivaCP/login.aspx
  - name: AcertivaCPWEB
    url: https://asertivacp.citasturnos.com/AsertivaCPWeb/welcome
  - name: AFP
    url: https://afp.citasturnos.com/AFP_ReservasWeb/welcome    
  - name: AFP
    url: https://afp.citasturnos.com/AFP_ReservasWeb/welcome    
  - name: DoctorCabreraCITASWEB
    url: https://drcabrera.citasturnos.com/DrCabreraWeb/welcome
  - name: DoctorCabreraCITASADM 
    url: https://drcabrera.citasturnos.com/DrCabrera/login.aspx
  - name: JurisdicciónInmobiliaria
    url: https://jurisdiccioninmobiliaria.citasturnos.com/CitasWebJurisdiccionInmobiliaria/welcome
  - name: Orbis
    url: https://orbis.citasturnos.com/OrbisWeb/welcome
  - name: Servicop
    url: https://servicoop.citasturnos.com/ServicoopWeb/welcome
  - name: Universal
    url: https://universal.citasturnos.com/Universalweb/welcome
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # https://sidesys.com/wp-content/uploads/2021/12/sidesys_logo.png
  #   logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  
  baseUrl: /Nube
  logoUrl: https://sidesys.com/wp-content/uploads/2021/12/sidesys_logo.png
  name: Monitor Nube Citas
  introTitle: "Monitor Nube Citas"
  introMessage: Monitor Nube Citas
  navbar:
    - title: Status
      href: /
    - title: Monitor
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
